name: Backend Continuous Integration

on:
  pull_request:
    branches: [main]
    paths:
      - 'starter/backend/**'
      - '.github/workflows/backend-ci.yaml'
  workflow_dispatch:

defaults:
  run:
    working-directory: starter/backend

jobs:
  lint:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Get the source
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Restore pipenv cache
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: be-pipenv-${{ runner.os }}-${{ hashFiles('starter/backend/Pipfile.lock') }}
          restore-keys: be-pipenv-${{ runner.os }}-

      - name: Install pipenv and packages
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run flake8
        run: pipenv run lint

  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Get the source
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Restore pipenv cache
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: be-pipenv-${{ runner.os }}-${{ hashFiles('starter/backend/Pipfile.lock') }}
          restore-keys: be-pipenv-${{ runner.os }}-

      - name: Install pipenv and packages
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run pytest
        run: pipenv run test

  build:
    name: Build docker image
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Get the source
        uses: actions/checkout@v4

      - name: Build the image
        run: docker build --tag movie-backend:${{ github.sha }} .